from app.models.expediente import Expediente
from app.models.plazo import Plazo
from app.models.documento import Documento
from app.models.actuacion import Actuacion
from app.models.regla import ReglaProcesal
from app.models.evento import EventoSistema
from app.models.estado import EstadoProcesal
from app.models.parte import Parte
from app.models.historial_estado import HistorialEstado